### ISSUE TITLE
Pet changing size

### ISSUE THREAD

**Issue by IanAMacMillan** [tonybaloney/vscode-pets#104]
https://user-images.githubusercontent.com/25908878/166217261-8e09a24e-613e-430f-92d9-e0f22c83d556.mov

It seems that the cat is changing sizes when it does stuff like chase the ball and swipe the curser. I'm not sure if this is on purpose.

**Comment by Harry-Hopkinson** [comment]
I think the idling animation is larger than the swiping animation. I do not do any animation so I do not have the sufficient skills required to fix this issue.

**Comment by MrSurana** [comment]
Tested with cat and dog. Issue is only with the brown cat due to the improper aspect ratio of gif files.

`media/cat/brown_walk_8fps.gif` image has aspect ratio of 1.769 with width and height of 115 × 65
`media/cat/brown_run_8fps.gif` image has aspect ratio of 1.176 with width and height of 100 × 85

All gif assets for any pet should have same aspect ratio.

@tonybaloney If you have the source files for these animation gifs, please change the dimensions and recreate assets.
