### ISSUE TITLE
Pet sprites aren't animating

### ISSUE THREAD

**Issue by TheMoonDawg** [tonybaloney/vscode-pets#63]
Recently, my pet sprites have stopped animating. They'll still move, but they're just gliding across the screen now. 

Here's my version info:

Version: 1.57.0 (Universal)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

I've tried reinstalling the extension as well as reloading my VSCode windows. Not sure what could be up.

Thanks for the amazing extension!! :D

**Comment by tonybaloney** [comment]
I had exactly the same issue yesterday. Nothing in the extension has changed. It's all since VS Code was updated. 
They're GIF's. Possibly a chrome change?

**Comment by TheMoonDawg** [comment]
Hmm yeah, now that I think about it, the issue only started when I updated VSCode as well.

**Comment by marcduiker** [comment]
Yup, have this issue as well. I'll ask around to see if anyone has an idea how to fix this.

**Comment by johnmbaughman** [comment]
Hmmm... this could explain why I'm seeing the non-returning extra pets. Ghosts of sessions past?

**Comment by effordDev** [comment]
Was anyone able to solve?

**Comment by SpLayzDK** [comment]
bump, we need a fix

**Comment by tonybaloney** [comment]
Just had a lightbulb moment and realised what was causing this. Pushed an update

**Comment by marcduiker** [comment]
OMG @tonybaloney you fixed it! I'm so happy with this, TY! 🙏

**Comment by tonybaloney** [comment]
IF anyone is curious what the fix was:

1. VS Code made a change to the static path for assets
2. When you change the src attribute of an image element it resets GIFs to the first frame
3. There was a check in the code to only set the image on a frame when it changed
4. That check would always say the image has changed, because VS Code was rewriting the URL
5. The images were actually animating, but they were being restarted to the first frame 8 times a second and so stuck on the first frame

So I changed it to check the last path of the URI and it no longer resets the animation 8 times a second

**Comment by TheMoonDawg** [comment]
My little pupper is back! Thanks man!
